### ISSUE TITLE
Bootstrap isn't loading proper data for pre-populated Date Field

### ISSUE THREAD

**Issue by JJediny** [DOE-NEPA/mapwarper#1]
## Loading today's date not date from field

![image](https://cloud.githubusercontent.com/assets/6350035/6100672/e5190b24-afe1-11e4-8ef7-e1b6f7f7ee15.png)

**Comment by eisemann** [comment]
Seems to be working now.

http://ec2-54-88-210-186.compute-1.amazonaws.com/nepa_documents/1540/edit

http://ec2-54-88-210-186.compute-1.amazonaws.com/nepa_documents/1540/nepa_milestones/10222/edit
