### ISSUE TITLE
jQuery history not updating tabs when using back button

### ISSUE THREAD

**Issue by eisemann** [DOE-NEPA/mapwarper#10]
goto http://warp.nepanode.anl.gov/maps/499
click metadata
click back

url updates but not tab

**Comment by JJediny** [comment]
Is it the jquery or is it that its not redirecting to the hashurl in #Show_tab first rather than the default view for /maps/499/

**Comment by JJediny** [comment]
Should have tested it myself (foot in mouth) its the jquery...

**Comment by JJediny** [comment]
maybe this is an opportunity to fix with Angular

**Comment by eisemann** [comment]
Looking into it now

**Comment by eisemann** [comment]
Ha, figured it out.  Just after the meeting started.
