### ISSUE TITLE
New NEPA Documents being created?

### ISSUE THREAD

**Issue by JJediny** [DOE-NEPA/mapwarper#11]
![image](https://cloud.githubusercontent.com/assets/6350035/6490979/1d4a23ae-c278-11e4-8857-b4d15830ca86.png)

**Comment by eisemann** [comment]
Seems to be working for me: 
http://warp.nepanode.anl.gov/nepa_documents?field=document_no&query=12345

But, your image clearly points out that I need to add some validations that require at least that the user enters a document number.
